defaults:
  - /../../../common/conf/base@
  - dataset/base
  - _self_

main:
  is_tested: true

module:
  _target_: src.tasks.appsilon.module.AppsilonModule

optimizer:
  lr: 0.001

trainer:
  max_epochs: 20
  batch_size: 128
  device: cpu
  monitored_metric:
    name: "Val/Acc"
    mode: max
  ckpt_path: null
  tag: null