hydra:
  run:
    dir: ../outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: null

main:
  is_tested: false

# TODO mogloby tu nie byc trainera i optimizera
trainer:
  device: [0]
  max_epochs: null
  monitored_metric: null
  wandb: false
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0

optimizer:
  use_scheduler: false

paths:
  root: ${hydra:runtime.cwd}
  data: ${paths.root}/data
