train:
  is_training: true
  scale: [0.08, 1.0]
  ratio: [0.75, 1.3333333333333333]
  auto_augment: rand-m9-mstd0.5-inc1
  interpolation: random
  re_prob: 0.25
  re_mode: pixel

val: &val_settings
  interpolation: bicubic
  crop_pct: 0.9
  is_training: false

test:
  <<: *val_settings