train:
  is_training: true
  input_size: [3, 384, 384]
  scale: [0.08, 1.0]
  ratio: [0.75, 1.3333333333333333]
  auto_augment: rand-m9-mstd0.5-inc1
  interpolation: random
  re_prob: 0.25
  re_mode: pixel

val: &val_settings
  is_training: false
  input_size: [3, 384, 384]
  interpolation: bicubic
  crop_pct: 0.9

test:
  <<: *val_settings