
defaults:
# Czyli /sciezka/do/FOLDERU!@nazwa_klucza: nazwa_configu
# !!! backslashe nie dzialaja
  - /../frontend@frontend: base_frontend
# Z "worka do worka"
  - _globals/globals@
# Defaultowa opcja. Sciezka w folderach zostanie wykorzystana jako sciezka w configu.
  - server/base
  - _self_

server:
  debug: false

frontend:
  enable_analytics: true
