# Czyli /sciezka/do/FOLDERU!@nazwa_klucza: nazwa_configu
defaults:
  - /../frontend@frontend: base_frontend
  - server/base_server
  - _self_

server:
  debug: false

frontend:
  enable_analytics: true
