defaults:
  - /../../../common/conf/base@
  - model/base
  - dataset/base
  - _self_

main:
  is_tested: true

module:
  _target_: src.tasks.gsn2.module.ObjectDetectionModule

optimizer:
  lr: 0.00001

trainer:
  max_epochs: 20
  batch_size: 16
  device: [0]
  monitored_metric:
    name: "Val/AccC7"
    mode: max
  ckpt_path: null
  tag: null

# TODO czy na pewno shared
shared:
  iou_threshold: 0.5