defaults:
  - /../../../common/conf/base@
  - dataset/augmentations/flowers_base
  - dataset/preprocessing/flowers_base
  - _self_

main:
  is_tested: true

module:
  _target_: src.tasks.flowers.module.FlowersModule

dataset:
  name: FlowersDataset
  visualization_mode: false

model:
  n_outputs: 17

optimizer:
  lr: 0.00001

trainer:
  max_epochs: 20
  batch_size: 16
  device: [0]
  monitored_metric:
    name: "Val/Acc1"
    mode: max
  ckpt_path: null
  tag: null