defaults:
  - /../../../common/conf/base@
  - dataset/augmentations/flowers_base
  - dataset/preprocessing/flowers_base
  - _self_

main:
  module_name: FlowersModule
  is_tested: true

dataset:
  name: FlowersDataset

model:
  n_outputs: 17

optimizer:
  lr: 0.00001

trainer:
  max_epochs: 20
  batch_size: 16
  device: [0]
  monitored_metric:
    name: "Val/Acc1"
    mode: max
