defaults:
  - /../../../common/conf/base@
  - dataset/base
  - _self_

main:
  is_tested: true

module:
  name: ShapesModule

optimizer:
  lr: 0.00001

trainer:
  max_epochs: 20
  batch_size: 16
  device: [0]
#  monitored_metric:
#    name: "Val/Acc1"
#    mode: max
